namespace EduardoBotv2.Core.Models.Enums
{
    public enum TelemetryEvents
    {
        LogPlayerLogin,
        LogPlayerCreate,
        LogPlayerPosition,
        LogPlayerAttack,
        LogItemPickup,
        LogItemEquip,
        LogItemUnequip,
        LogVehicleRide,
        LogMatchDefinition,
        LogMatchStart,
        LogGameStatePeriodic,
        LogVehicleLeave,
        LogPlayerTakeDamage,
        LogPlayerLogout,
        LogItemAttach,
        LogItemDrop,
        LogPlayerKill,
        LogItemDetach,
        LogItemUse,
        LogCarePackageSpawn,
        LogVehicleDestroy,
        LogCarePackageLand,
        LogMatchEnd
    }
}